config/routes.rb
Rails.application.routes.draw do
  resources :guests, only: %i[new create index show destroy]
  resources :contacts, only: %i[new create index show destroy]

  get '/', to: 'home#index', as: 'root'
  get '/:id', to: 'home#test', as: 'test'
  get 'contacts/:id', to: 'contacts#new'
  post 'guests', to: 'guests#create' # AJAX

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

ERROR_MSG = 'E-mail adress does not seem to be valid'

class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/,
                              message: ERROR_MSG }
end

app/models/guest.rb
class Guest < ApplicationRecord
  validates :GUID, :URL, :timestamp, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: %i[show edit update destroy]

  def index
    @contacts = Contact.all
  end

  def show; end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact, notice: 'Contact created.'
    else
      render :new
    end
  end

  private

  def find_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[create]

  def index
    @guests = Guest.last(50).reverse
  end

  def show; end

  def new
    @guest = Guest.new
  end

  def edit; end

  def create
    # Here from Rails.AJAX post
    @guest = Guest.new(guest_params)
    respond_to do |format|
      if @guest.save
        format.html { redirect_to guests_url, notice: 'New guest OK.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.json { render :show }
      end
    end
  end

  def update
    if @guest.update(guest_params)
      redirect_to @guest
    else
      render :edit
    end
  end

  private

  def guest_params
    params.permit(:GUID, :URL, :timestamp)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def test; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/new.html.erb
<p>Pease fill in your name and email here so we can get in touch with you!</p>

<%= simple_form_for(@contact) do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.submit %>
<% end %>

app/views/contacts/show.html.erb
<P>Hello Client</P>

app/views/guests/index.html.erb
<p>The latest vistors:<p>
  <table class="table">
    <tbody>
      <% @guests.each do |guest| %>
        <tr>
          <td>ID: <%= guest.id %></td>
          <td>GUID: <%= guest.GUID %></td>
          <td>FROM: @<%= guest.URL %></td>
          <td>AT: <%= guest.timestamp %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/home/index.html.erb
<h1>HOME PAGE</h1>

<h4>This is the home page to be registered when visited</h4>

app/views/home/test.html.erb
<h1>TEST PAGE</h1>

<h4>This is just an empty page to be registered when visited</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JH TEST ICASEI</title>
  </head>

  <body>
    <%= render 'shared/common_links' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
</html>

app/views/shared/_common_links.html.erb
        <a class="nav-link" href="/">Home </a>

        <p> Icasei Test Rastreamente </p>

        <a class="nav-link" href="/test">Test</a>

        <p class="nav-link"><%= link_to 'Contact', new_contact_path %></p>

        <a class="nav-link" href="/guests">Visitors </a>